In [1]:
datos=spark.read.csv("/FileStore/tables/train.csv",header=True,inferSchema=True)

In [2]:
datos.printSchema()

In [3]:
datos.count()

In [4]:
datos.select("PassengerId","Cabin").show(20)

In [5]:
datos.groupBy("Sex").count().show()

In [6]:
datos.crosstab("Sex","Survived").show()

In [7]:
datos.crosstab("Pclass","Survived").show()

In [8]:
datos.crosstab("Embarked","Survived").show()

In [9]:
datosOk=datos.na.drop(subset=['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked'])

In [10]:
datosOk.count(),datos.count()

In [11]:
datos.subtract(datosOk).show()